const express = require("express");
const auth = require("../middleware/auth");
const { Category, validate } = require("../models/Category");
const router = express.Router();

// GET Categories for a user
router.get("/", auth, async (req, res) => {
  // Extract info from the user tag(user tag generated by middleware -> auth)
  const categories = await Category.find({ userId: req.user._id });
  return res.send({ data: categories });
  // Return the information of the user
});

// POST a New Category
router.post("/", auth, async (req, res) => {
  // Validate Request Body
  const { error } = validate(req.body);

  if (error) return res.status(400).send({ message: error.details[0].message });

  const category = new Category({
    title: req.body.title,
    userId: req.user._id,
  });

  await category.save();
  return res.send({ data: category });
});

module.exports = router;
